---

- hosts: routers
  gather_facts: false
  connection: network_cli
  tasks:

  - name: make extended acl
    ios_config:
      lines:
      - 10 permit ip any any 

      parents: ip access-list extended test
      before: no ip access-list extended test
      match: exact

  
...