---

- hosts: routers
  gather_facts: false
  connection: network_cli
  tasks:

  - name: make extended acl
    ios_config:
      lines:
      - 10 deny tcp any any eq 23
      - 20 permit ip any any 
      

      parents: ip access-list extended test
      before: no ip access-list extended test
      match: exact

  - name: apply acl
    ios_config:
      lines:
      - ip access-group test in 
      parents: interface GigabitEthernet1


  
...