---

- hosts: routers
  gather_facts: false

  tasks:

    - name: configure
      cisco.ios.ios_config:
        src: /etc/ansible/roles/DYN-ANSIBLE/config.txt


    - name: save
      cisco.ios.ios_config:
        save_when: modified
      
...