---

- hosts: routers
  gather_facts: false
  connection: network_cli
  tasks:

  - name: base
    ios_config:
      lines:
      - hostname CSR
      - enable secret 5 cisco
      - aaa new-model
      - no ip domain lookup
      - ip domain name danny.local
      - username danny privilege 15 password 0 cisco
      - username root privilege 15 password 0 cisco
      

...