---
# Config voor CSR02
- hosts: 172.16.60.2
  gather_facts: false
  connection: network_cli
  tasks:

  - name: base
    ios_config:
      lines:
      - hostname R2
      - enable secret 5 cisco
      - aaa new-model
      - no ip domain lookup
      - ip domain name danny.local
      - username danny privilege 15 password 0 cisco
      - username root privilege 15 password 0 cisco


- hosts: 172.16.60.2
  gather_facts: false
  connection: network_cli
  tasks:


  - name: configure interface settings
    ios_config:
      lines:
      - description WAN link
      - ip address 172.16.30.2 255.255.255.248
      - no shutdown
      parents: interface GigabitEthernet1


  - name: configure interface settings
    ios_config:
      lines:
      - description LAN link
      - ip address 10.1.3.1 255.255.255.0
      - no shutdown
      parents: interface GigabitEthernet2 


  - name: configure loopback
    ios_config:
      lines:
      - ip address 2.2.2.2 255.255.255.0  
      parents: interface loopback 1 


  - name: default route
    ios_config:
      lines:
      - ip route 0.0.0.0 0.0.0.0 172.16.30.1


# Config voor CSR03
- hosts: 172.16.60.3
  gather_facts: false
  connection: network_cli
  tasks:

  - name: base
    ios_config:
      lines:
      - hostname R3
      - enable secret 5 cisco
      - aaa new-model
      - no ip domain lookup
      - ip domain name danny.local
      - username danny privilege 15 password 0 cisco
      - username root privilege 15 password 0 cisco


- hosts: 172.16.60.3
  gather_facts: false
  connection: network_cli
  tasks:


  - name: configure interface settings
    ios_config:
      lines:
      - description WAN link
      - ip address 172.16.30.4 255.255.255.248
      - no shutdown
      parents: interface GigabitEthernet1


  - name: configure interface settings
    ios_config:
      lines:
      - description LAN link
      - ip address 10.1.3.2 255.255.255.0
      - no shutdown
      parents: interface GigabitEthernet2
  

  - name: configure loopback
    ios_config:
      lines:
        - ip address 3.3.3.3 255.255.255.0  
      parents: interface loopback 1 

    
  - name: default route
    ios_config:
      lines:
      - ip route 0.0.0.0 0.0.0.0 172.16.30.1


...