---

- hosts: 172.16.60.2
  gather_facts: false
  connection: network_cli
  tasks:

  - name: make dhcp pool
    ios_config:
      lines:
      - network 10.1.3.0 255.255.255.0
      - default-router 10.1.3.1
      parents: ip dhcp pool pool1
      before: ip dhcp excluded-address 10.1.3.1 10.1.3.64
    
  
...