---

- hosts: 172.16.60.2
  gather_facts: false
  connection: network_cli
  tasks:


  - name: configure interface settings
    ios_config:
      lines:
      - description WAN link
      - ip address 172.16.30.2 255.255.255.248
      parents: interface GigabitEthernet1


  - name: configure interface settings
    ios_config:
      lines:
      - description LAN link
      - ip address 10.1.3.1 255.255.255.0
      parents: interface GigabitEthernet2
    
    
...