---

- hosts: routers
  gather_facts: false
  connection: network_cli
  tasks:


  - name: configure inside
    ios_config:
      lines:
      - ip nat inside
      parents: interface GigabitEthernet2


  - name: configure outside
    ios_config:
      lines:
      - ip nat outside
      parents: interface GigabitEthernet1


  - name: make acl
    ios_config:
      lines:
      - access-list 200 permit ip 10.1.3.0 0.0.0.255 any

  
  - name: configure overload
    ios_config:
      lines: 
      - ip nat inside source list 200 interface GigabitEthernet1 overload


...