---

- hosts: routers
  gather_facts: false

  tasks:

    - name: configure ospf
      cisco.ios.ios_config:
        lines:
        - router-id 1.1.1.1
        - network 172.16.30.0 0.0.0.7 area 0
        parents: router ospf 100

  
...