---

- hosts: 172.16.60.2
  gather_facts: false
  connection: network_cli
  tasks:

  - name: configure ospf
    ios_config:
      lines:
      - router-id 2.2.2.2
      - network 172.16.30.0 0.0.0.7 area 0
      - network 10.1.3.0 0.0.0.255 area 0
      parents: router ospf 100

- hosts: 172.16.60.3
  gather_facts: false
  connection: network_cli
  tasks:

  - name: configure ospf
    ios_config:
      lines:
      - router-id 3.3.3.3
      - network 172.16.30.0 0.0.0.7 area 0
      - network 10.1.3.0 0.0.0.255 area 0
      parents: router ospf 100  

  
...